### ISSUE TITLE
place_id and types fields are absent in the response

### ISSUE THREAD

**Issue by chester89** [bcuff/GeocodeSharp#11]
When I poke Geocoding service using Fiddler, I noticed there's a couple of fields missing - namely "place_id" and "types"
![google_geocoding](https://cloud.githubusercontent.com/assets/190332/12581540/507fadfc-c448-11e5-9e55-f6f9c0183713.jpg)
Would you mind if I do the PR to add them?

**Comment by bcuff** [comment]
Sure. add them. thanks!

**Comment by chester89** [comment]
I also added a language parameter (for localization). Can you publish a new
version on Nuget?

2016-01-26 18:34 GMT+03:00 Brandon <notifications@github.com>:

> Sure. add them. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcuff/GeocodeSharp/issues/11#issuecomment-175080181>.
>



-- 
Yours faithfully,
Gleb

**Comment by bcuff** [comment]
Cool. will publish after your PR is merged. I left a comment for you to address first.

Thanks!
